name: Test Package Commands

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, dom, fileinfo, sqlite, gd
          coverage: none

      - name: Install Laravel Orchestral (Testbench)
        run: |
          composer update --prefer-stable --no-interaction

      - name: Run Pest or PHPUnit Tests
        run: vendor/bin/pest --compact --ci