name: Test Package Commands

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, dom, fileinfo, sqlite, gd
          coverage: xdebug

      - name: Install Dependencies
        run: |
          composer update --prefer-stable --no-interaction

      - name: Run Pest with Coverage Report
        run: vendor/bin/pest --coverage-html build/coverage --compact --ci

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: post-coverage-report
          path: build/coverage